[build-system]
requires = ["setuptools>=61", "setuptools_scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netconf-client"
dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
version = { use_scm_version = true }
dependencies = { file = "requirements.txt" }
